# Generated by Django 3.0.7 on 2020-06-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('emailId', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('dateOfBirth', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('adminRoleType', models.CharField(max_length=30)),
                ('isActive', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
